### ISSUE TITLE
Support Progress (method: '$/progress')

### ISSUE THREAD

**Issue by kkharji** [apple/sourcekit-lsp#577]
Hello,

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#progress

It would be great to support progress as it helper users of the server to have some form of feedback on server initialization

Thanks

**Comment by ahoppen** [comment]
I agree that having that functionality would be great but it’s unlikely that it will be something that we’ll be able to implement in the near future because none of the infrastructure in sourcekitd (which is providing the semantic functionality for Swift in SourceKit-LSP) is set up to provide progress notifications. 

Specifically regarding server initialization: SourceKit-LSP doesn’t actually do a lot of work when the server is initialized because there is no background indexing going on (we require you to build the project to update the index [Link](https://github.com/apple/sourcekit-lsp#caveats)). So I don’t think progress for initialization would pretty much just finish immediately.

**Comment by ahoppen** [comment]
rdar://96198579

**Comment by ahoppen** [comment]
Since we don’t have any data regarding progress from sourcekitd and by the way things are defined, there’s no way we will get progress data in the future, this is not actionable, so I’m closing it. 

We can open more specific issues about progress support once SourceKit-LSP has some sort of long-running operations for which it makes sense to provide progress.
