### ISSUE TITLE
Align the set of cross-compilation arguments with SwiftPM

### ISSUE THREAD

**Issue by stevapple** [apple/sourcekit-lsp#601]
SourceKit-LSP is missing most of the dedicated arguments for cross-compilation that was introduced in SwiftPM, which makes it hard to use when it comes to cross-compiling.

Ideally it should gain the same level of support with `swift build`. The missing ones are:
- `--destination <destination>`
- `--triple <triple>`
- `--sdk <sdk>`
- `--toolchain <toolchain>`

**Comment by stevapple** [comment]
Note that there was an attempt for `--destination` at #330, but it was suspended.

**Comment by stevapple** [comment]
It would be better if `destination.json` can be hot-reloaded so the IDE can have direct control on the settings.

**Comment by ahoppen** [comment]
rdar://97961537

**Comment by filip-sakel** [comment]
Hello! Sorry for resurrecting this, but SwiftWasm is currently quite limited on VS Code because of this issue. Was there something intrinsically wrong with https://github.com/apple/sourcekit-lsp/pull/330 or was there just a problem with tests failing? I'm wondering how I could get started (if I need to be aware of any challenges, any useful pointers) to hopefully fix this issue.

**Comment by MaxDesiatov** [comment]
I've left a comment on that PR, but additionally I think we need an additional LSP message to allow client extensions to switch between available Swift SDKs, not just triples. That probably also implies querying for a list of already installed SDKs so that a user is able to select one from the list.

**Comment by MaxDesiatov** [comment]
Closing as a duplicate of https://github.com/apple/sourcekit-lsp/issues/786.
