### ISSUE TITLE
Jump to definition requires a reload after build

### ISSUE THREAD

**Issue by adam-fowler** [apple/sourcekit-lsp#620]
If I load a project with dependencies into VS Code which has not been built when I right click on a symbol to go to definition (run a textDocument/definition request) it returns an empty result. This is a known issue.

If I then build the project and repeat I still get an empty result. I would assume once the project is built SourceKit-LSP should be able to return a position for the symbol.

I have to restart VS Code (ie restart the SourceKit-LSP server) for SourceKit-LSP to return a valid position for the symbol.

**Comment by ahoppen** [comment]
rdar://99329579

**Comment by adam-fowler** [comment]
This look like it is resolved, will re-open if I see it again

**Comment by adam-fowler** [comment]
Re-opening saw it again

**Comment by adam-fowler** [comment]
Actually it is just slow to respond. Is there a way we can indicate the LSP server is loading the index after a build, or whatever it is doing post build that means it doesn't have the built symbols available.

**Comment by ahoppen** [comment]
I’m adding a progress indicator for package reloading in https://github.com/apple/sourcekit-lsp/pull/767. That’s all I can think of that might take a non-trivial amount of time and happens on the SourceKit-LSP side after the project has been modified.

**Comment by ahoppen** [comment]
Oh, and now I’ve been able to reproduce the issue as well, independent of the work done progress for package loading.

The issue appears to be that we don’t get compiler arguments if the dependencies have not been checked out and we don’t reload the package after the dependencies are checked out.

Steps to reproduce:
- Set `SOURCEKIT_LOGGING=99` in the VSCode Swift plugin settings
- Clone the soucekit-lsp repository
- `swift package reset`
- Open the project in VSCode
- Open DocumentTokens.swift
- Notice that DocumentTokens.swift gets opened with compiler arguments
- Run a build
- Close and re-open DocumentTokens.swift
- Notice that it still gets opened without compiler arguments

**Comment by ahoppen** [comment]
What’s happening is that after building, you need to make an edit to the file to get jump-to-definition working. Could that match what you’ve been seeing @adam-fowler?

On a technical level
- When we open the file, we build an AST for it. That AST has errors because the dependent modules haven’t been built yet.
- Now we build the dependent modules and the dependent module files exist
- If you now do a jump to definition request again, we perform a cursor info request to get the USR of the symbol we do jump-to-definition for but since the file hasn’t changed, cursor info re-uses the previously built AST and is thus unable to resolve the symbol (because at the point that the AST was created the module that contains the symbol didn’t exist yet)
- If you make an edit to the file (that’s not an edit inside a comment), we stop re-using the previously built AST. At that point, you see semantic highlighting appearing for the symbol in the other module and jump-to-definition starts working.

The way I would like to fix this, is to migrate cursor info to solver-based, which removes the need for this AST reuse altogether. This is a long-term effort though. I don’t have a good idea for a short-term workaround and since things recover after the first edit, I believe there’s nothing immediate we need to or should do here.

**Comment by adam-fowler** [comment]
> What’s happening is that after building, you need to make an edit to the file to get jump-to-definition working. Could that match what you’ve been seeing @adam-fowler?

I'll have to check that. It could be.

Given you are saying the correct solution is a long-term effort is there anything temporary I could do to resolve this issue. I know when a build finishes could I get VSCode to send some request, notification that would trigger an AST rebuild

**Comment by ahoppen** [comment]
Other than making an edit to the file, unfortunately I don’t think there’s anything you could do here to work around the issue. I’m sorry.
