### ISSUE TITLE
Jump to definition stdlib should be able to goto source instead of .swiftinterface

### ISSUE THREAD

**Issue by vishesh** [apple/sourcekit-lsp#795]
When jumping to definition for a stdlib symbol, we reach the swiftinterface file, which is usually fine, but sometimes it is nice to be able to see the implementation itself than just signatures, understand what that method does better. Lot of other language servers do that as well (Java, C++, Rust, Python) and its been often useful I think.

**Comment by ahoppen** [comment]
The Swift toolchain doesn’t ship with the source code of the standard library and there isn’t any way to translate assembly back into Swift. So, it’s just impossible to show the implementation of these functions. So, I’m closing the issue.

Note that you can look the implementation of these functions on GitHub (https://github.com/apple/swift/tree/main/stdlib). Most likely the implementation of the stdlib types and functions hasn’t changed (much) since the toolchain that you have installed, so it’s probably a good reference point. But there’s no way to map from your project to these implementation files because
- There is no 1:1 mapping of toolchains to open source commits. For example the Swift toolchains included in Xcode might contain some changes that aren’t present in the open source repository
- Many standard library files in the GitHub repo need to be pre-processed using `gyb` to generate valid Swift code
- The GitHub repository isn’t indexed, so we don’t even know where to jump to
- You would need internet access to do this anyway
