### ISSUE TITLE
Convert `ManualMainFilesProvider` and `BSMDelegate` to be actors

### ISSUE THREAD

**Issue by ahoppen** [apple/sourcekit-lsp#868]
Both `ManualMainFilesProvider` and `BSMDelegate` in `BuildSystemManagerTests.swift` are classes with a queue. We should be able to convert both of them to actors.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://116703668

**Comment by joehsieh** [comment]
may i take this issue if it's still unassigned?

**Comment by ahoppen** [comment]
Sure, thank you!

**Comment by joehsieh** [comment]
**[Discussion]**
Hello @ahoppen i'd like to discuss an issue that i found after the investigation.
There are two classes conforming protocol `MainFilesProvider`. One (ManualMainFilesProvider) is for the testing, another one is for the implementation (IndexStoreDB). I noticed the serial queue in ManualMainFilesProvider is just only for the purpose of testing not for the implementation. (can check Investigation result below)
Hence, once we convert the queue to be an actor. For the same purpose of testing, the func mainFilesContainingFile in the protocol MainFilesProvider would be changed ([the draft PR](https://github.com/apple/sourcekit-lsp/pull/917))
```
from 
func mainFilesContainingFile(_: DocumentURI) -> Set<DocumentURI>
to 
func mainFilesContainingFile(_: DocumentURI) async -> Set<DocumentURI>
```
to allow actors to conform, which is unexpected because `async` is unnecessary for the implementation. 

Instead of converting ManualMainFilesProvider to be an actor, i think we can make mainFiles immutable and update related code in BuildSystemManagerTests. (i'll give it a try soon) What do you think? 

**Investigation result:**
- class ManualMainFilesProvider

mainFiles is a member variable, and we need a serial queue to maintain it make sure it's thread-safe since mainFiles is possibly updated with the setter of mainFiles in unit testing.

```
private final class ManualMainFilesProvider: MainFilesProvider {
  let lock: DispatchQueue = DispatchQueue(label: "\(ManualMainFilesProvider.self)-lock")
  private var _mainFiles: [DocumentURI: Set<DocumentURI>] = [:]
  var mainFiles: [DocumentURI: Set<DocumentURI>] {
    get { lock.sync { _mainFiles } }
    set { lock.sync { _mainFiles = newValue } }
  }

  func mainFilesContainingFile(_ file: DocumentURI) -> Set<DocumentURI> {
    if let result = mainFiles[file] {
      return result
    }
    return Set()
  }
}
```

- class IndexStoreDB
`mainFiles` is not a member variable, mainFiles is derived based on other info. Therefore, there is no queue in the IndexStoreDB to ensure mainFiles is thread-safe.

```
  public func mainFilesContainingFile(_ uri: DocumentURI) -> Set<DocumentURI> {
    let mainFiles: Set<DocumentURI>
    if let url = uri.fileURL {
      mainFiles = Set(
        self.mainFilesContainingFile(path: url.path)
          .lazy.map({ DocumentURI(URL(fileURLWithPath: $0, isDirectory: false)) })
      )
    } else {
      mainFiles = []
    }
    logger.info("mainFilesContainingFile(\(uri.forLogging)) -> \(mainFiles)")
    return mainFiles
  }
```

**Comment by joehsieh** [comment]
For BSMDelegate, it's already an actor, but an [unused queue](https://github.com/apple/sourcekit-lsp/blob/main/Tests/SKCoreTests/BuildSystemManagerTests.swift#L476) is still in it. i'll remove it.

**Comment by ahoppen** [comment]
Making `MainFilesProvider.mainFilesContainingFile` an `async` function is a totally fine thing to do IMO. Currently, `IndexStoreDB` is the only main file provider and it happens to be synchronous but getting the main files could be an expensive operation (eg. if we asked a build server from the Build Server Protocol for main files, which would require inter-process communication – note that this isn’t implemented at the moment but it could be possible) and thus having it be `async` makes total sense to me.

**Comment by joehsieh** [comment]
understood, func `mainFilesContainingFile` for implementation is expected to be async eventually, so let me proceed with my implementation. thanks for the info!

**Comment by ahoppen** [comment]
Fixed by https://github.com/apple/sourcekit-lsp/pull/917
