### ISSUE TITLE
Report CodeActions for Fix-Its produced by swift-syntax

### ISSUE THREAD

**Issue by ahoppen** [apple/sourcekit-lsp#909]
Address this `FIXME` https://github.com/apple/sourcekit-lsp/pull/902/files#diff-6147b806788b196876d46885643488f44c48b14791d7adc3ef5d2d91b361bd11R74-R76 and report CodeActions for the Fix-Its produced by the integrated Swift parser if we don’t have compiler arguments.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://117176551

**Comment by joehsieh** [comment]
Just to clarify the requirements

> // FIXME: Once https://github.com/apple/swift-syntax/pull/2226 is merged and
> // FixItApplier is public, use it to compute the edits that should be
> // applied to the source.
> https://github.com/apple/sourcekit-lsp/pull/902/files#diff-6147b806788b196876d46885643488f44c48b14791d7adc3ef5d2d91b361bd11R74-R76 

1. FixItApplier is under [_SwiftSyntaxTestSupport](https://github.com/apple/swift-syntax/tree/main/Sources/_SwiftSyntaxTestSupport) to support testing, so FixItApplier won't be used in [Diagnostic.swift](https://github.com/apple/sourcekit-lsp/pull/902/files#diff-6147b806788b196876d46885643488f44c48b14791d7adc3ef5d2d91b361bd11)
Instead, what we need is a func in Diagnostic.swift to convert `FixIt.Change` to `TextEdit `.
pseudo code
```
extension FixIt.Change {
  func edit(snapshot: DocumentSnapshot) -> TextEdit? {
    switch self {
      case .replace(let oldNode, let newNode):
        return TextEdit(...)
      case .replaceLeadingTrivia(let token, let newTrivia):
        return TextEdit(...)
      case .replaceTrailingTrivia(let token, let newTrivia):
        return TextEdit(...)
    }
  }
}
```

so that we can convert the fixIt to an array of TextEdit here.
```
  init?(_ fixIt: FixIt, in snapshot: DocumentSnapshot) {
    // FIXME: Once https://github.com/apple/swift-syntax/pull/2226 is merged and
    // FixItApplier is public, use it to compute the edits that should be
    // applied to the source.
    var edits = [TextEdit]()
    for change in fixIt.changes {
      if let edit = change.edit(snapshot: snapshot) {
        edits.append(edit)
      }
    }
...
}
```

> report CodeActions for the Fix-Its produced by the integrated Swift parser if we don’t have compiler arguments.

2. what are these compiler arguments? 

Let me know if it's a urgent issue we need to fix in near future. i'll work on other ticket if needed. Thanks!

**Comment by ahoppen** [comment]
Fixed by https://github.com/apple/swift-syntax/pull/2314
