### ISSUE TITLE
Fix failed SemanticTokensTests

### ISSUE THREAD

**Issue by joehsieh** [apple/sourcekit-lsp#940]
Got below message after running `swift test` on main.
I was wondering if it's something wrong with my env, so i git-bisect the commits, and it seems this tests were failed after we merged this [PR](https://github.com/apple/sourcekit-lsp/pull/912) on Oct, 25.
But why it pass on CI, but failed on my side.

```
Test Case '-[SourceKitLSPTests.SemanticTokensTests testSemanticTokens]' failed (0.109 seconds).
Test Case '-[SourceKitLSPTests.SemanticTokensTests testSemanticTokensForStaticMethods]' failed (0.113 seconds).
...
```

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://117590581

**Comment by ahoppen** [comment]
Yeah, I was semi-aware of this. The issue is that sourcekit-lsp now uses the semantic token request to sourcekitd that was introduced by https://github.com/apple/swift/pull/69294. But the sourcekitd that is being used from your Xcode installation of course doesn’t have that sourcekitd request yet. 

To fix that, you can download a recent development snapshot from https://www.swift.org/download/#trunk-development-main and set the `SOURCEKIT_TOOLCHAIN_DIR` environment variable to the downloaded toolchain - that’s what I’ve been doing. But of course that’s not a great experience. I opened https://github.com/apple/sourcekit-lsp/pull/947 to skip the semantic tokens tests if sourcekitd doesn’t have the semantic tokens request.

**Comment by joehsieh** [comment]
> To fix that, you can download a recent development snapshot from https://www.swift.org/download/#trunk-development-main and set the SOURCEKIT_TOOLCHAIN_DIR environment variable to the downloaded toolchain - that’s what I’ve been doing.

Thanks! it's working
